ticketee/config/routes.rb
Ticketee::Application.routes.draw do
  root :to => "projects#index"
  resources :projects
  

end

ticketee/app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true
end

ticketee/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

ticketee/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  
  def index
  end
  
  def new
    @project = Project.new
  end
  
  
  def create 
    @project = Project.new(params[:project]) 
   if @project.save 
      flash[:notice] = "Project has been created." 
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render :action => "new" 
    end
  end
  
  def show 
    @project = Project.find(params[:id])
  end
  
end

ticketee/app/helpers/application_helper.rb
module ApplicationHelper

  def title(*parts)
    unless parts.empty? 
      content_for :title do
        (parts << "Ticketee").join(" - ") unless parts.empty? 
      end
    end 
  end  
end

ticketee/app/helpers/projects_helper.rb
module ProjectsHelper
end

ticketee/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  	<title> 
		<% if content_for?(:title) %>
			<%= yield(:title) %> 
		<% else %>
			Ticketee 
		<% end %>
	</title>
	
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% flash.each do |key, value| %>
		<div class='flash' id='<%= key %>'>
			 <%= value %>
		</div> 
	<% end %>


<%= yield %>

</body>
</html>

ticketee/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %> 
<%= f.error_messages %>
	<p>
		<%= f.label :name, "Nom" %>
		<%= f.text_field :name %>
	</p>
	<%= f.submit %>
<% end %>

ticketee/app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>

ticketee/app/views/projects/new.html.erb
<h2>New project</h2>
 <%= render "form" %>

ticketee/app/views/projects/show.html.erb
<h2><%= @project.name %></h2>

<% title(@project.name, "Projects") %>